"""
This type stub file was generated by pyright.
"""

import six
from promise import Promise, is_thenable
from graphql.error import GraphQLError, format_error as format_graphql_error
from graphene.types.schema import Schema

def default_format_error(error): # -> dict[str, text_type]:
    ...

def format_execution_result(execution_result, format_error): # -> dict[Unknown, Unknown] | None:
    ...

class Client:
    def __init__(self, schema, format_error=..., **execute_options) -> None:
        ...
    
    def format_result(self, result): # -> dict[Unknown, Unknown] | None:
        ...
    
    def execute(self, *args, **kwargs): # -> Promise[Unknown] | dict[Unknown, Unknown] | None:
        ...
    


