"""
This type stub file was generated by pyright.
"""

from .scalars import Scalar

class Date(Scalar):
    """
    The `Date` scalar type represents a Date
    value as specified by
    [iso8601](https://en.wikipedia.org/wiki/ISO_8601).
    """
    @staticmethod
    def serialize(date): # -> str:
        ...
    
    @classmethod
    def parse_literal(cls, node): # -> date | None:
        ...
    
    @staticmethod
    def parse_value(value): # -> date | None:
        ...
    


class DateTime(Scalar):
    """
    The `DateTime` scalar type represents a DateTime
    value as specified by
    [iso8601](https://en.wikipedia.org/wiki/ISO_8601).
    """
    @staticmethod
    def serialize(dt): # -> str:
        ...
    
    @classmethod
    def parse_literal(cls, node): # -> datetime | None:
        ...
    
    @staticmethod
    def parse_value(value): # -> datetime | None:
        ...
    


class Time(Scalar):
    """
    The `Time` scalar type represents a Time value as
    specified by
    [iso8601](https://en.wikipedia.org/wiki/ISO_8601).
    """
    @staticmethod
    def serialize(time): # -> str:
        ...
    
    @classmethod
    def parse_literal(cls, node): # -> time | None:
        ...
    
    @classmethod
    def parse_value(cls, value): # -> time | None:
        ...
    


