"""
This type stub file was generated by pyright.
"""

from .scalars import Scalar

class Decimal(Scalar):
    """
    The `Decimal` scalar type represents a python Decimal.
    """
    @staticmethod
    def serialize(dec): # -> str:
        ...
    
    @classmethod
    def parse_literal(cls, node): # -> Decimal | None:
        ...
    
    @staticmethod
    def parse_value(value): # -> Decimal | None:
        ...
    


