"""
This type stub file was generated by pyright.
"""

def attr_resolver(attname, default_value, root, info, **args): # -> Any | None:
    ...

def dict_resolver(attname, default_value, root, info, **args):
    ...

def dict_or_attr_resolver(attname, default_value, root, info, **args): # -> Any | None:
    ...

default_resolver = ...
def set_default_resolver(resolver): # -> None:
    ...

def get_default_resolver(): # -> (attname: Unknown, default_value: Unknown, root: Unknown, info: Unknown, **args: Unknown) -> (Unknown | Any | None):
    ...

