"""
This type stub file was generated by pyright.
"""

from typing import Union

def sanitize_if_forward_ref(subscripted_type: type) -> Union[type, str]:
    ...

def is_sequence(tp): # -> bool:
    ...

def is_raw_sequence(dependency): # -> bool:
    ...

