"""
This type stub file was generated by pyright.
"""

from .deprecated import deprecated

@deprecated("This function is deprecated")
def resolve_only_args(func): # -> _Wrapped[(...), Unknown, (root: Unknown, info: Unknown, **args: Unknown), Unknown]:
    ...

