"""
This type stub file was generated by pyright.
"""

from injectable.errors.autowiring_error import AutowiringError
from injectable.errors.injection_error import InjectionError

"""
Custom exceptions raised by injectable.
"""
__all__ = ["AutowiringError", "InjectionError"]
