"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Sequence, Set, Type, TypeVar, Union
from injectable.container.injectable import Injectable

T = TypeVar("T")
class RegistryType(Enum):
    CLASS = ...
    QUALIFIER = ...


def get_dependency_registry_type(dependency: Union[Type[T], str]) -> RegistryType:
    ...

def get_namespace_injectables(dependency_name: str, registry_type: RegistryType, namespace: str) -> Set[Injectable]:
    ...

def filter_by_group(matches: Set[Injectable], group: str = ..., exclude_groups: Sequence[str] = ...) -> Set[Injectable]:
    ...

def resolve_single_injectable(dependency_name: str, registry_type: RegistryType, matches: Set[Injectable]) -> Injectable:
    ...

