"""
This type stub file was generated by pyright.
"""

from typing import Set, Union
from injectable.container.injectable import Injectable

def clear_injectables(dependency: Union[type, str], namespace: str = ...) -> Set[Injectable]:
    """
    Utility function to clear all injectables registered for the dependency in a given
    namespace. Returns a set containing all cleared injectables.

    :param dependency: class or qualifier of the dependency.
    :param namespace: (optional) namespace in which the injectable will be registered.
            Defaults to :const:`injectable.constants.DEFAULT_NAMESPACE`.

    Usage::

      >>> from injectable.testing import clear_injectables
      >>> clear_injectables("foo")

    .. versionadded:: 3.3.0
    """
    ...

