"""
This type stub file was generated by pyright.
"""

def reset_injection_container(): # -> None:
    """
    Utility function to reset the injection container, clearing all injectables
    registered from all namespaces and reseting the record for already scanned files.

    Usage::

      >>> from injectable.testing import reset_injection_container
      >>> reset_injection_container()

    .. versionadded:: 3.4.0
    """
    ...

