"""
This type stub file was generated by pyright.
"""

from typing import AnyStr, Union

def get_caller_filepath(steps_back: int = ...) -> AnyStr:
    """
    Utility function to get the caller's filepath using inspection.

    :param steps_back: (optional) 1 step back in the call stack would return the file of
        the caller of this function. Defaults to 2, i.e. the path of the file of the
        caller of this function's caller.
    """
    ...

def get_dependency_name(dependency: Union[type, callable, str]) -> str:
    ...

