"""
This type stub file was generated by pyright.
"""

from typing import Optional
from injectable.container.injectable import Injectable

class Namespace:
    def __init__(self) -> None:
        ...
    
    def register_injectable(self, injectable: Injectable, klass: Optional[type] = ..., qualifier: Optional[str] = ..., propagate: bool = ...): # -> None:
        ...
    


